### 매장 등록
POST http://localhost:8080/shop
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QxMEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NQU5BR0VSIiwiaWF0IjoxNzM4NTEwNzUyLCJleHAiOjE3MzkwMTA3NTJ9.SKzbY3OyOPxKScFVoid9JK387p04qj5izQ0XU9aiRyA

{
  "name": "백우동",
  "ownerId": 2,
  "address": "서울시 관악구 신림역주변",
  "addressDetail": "201호",
  "lat": 37.48794321267735,
  "lng": 126.9343846451034,
  "description": "새로된 우동집",
  "openTime": 9,
  "closeTime": 24,
  "workingDays": [
    "SUNDAY",
    "MONDAY",
    "TUESDAY",
    "WEDNESDAY",
    "THURSDAY",
    "FRIDAY",
    "SATURDAY"
  ]
}

### 매장 삭제
DELETE http://localhost:8080/shop?name=백다방
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QxMEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NQU5BR0VSIiwiaWF0IjoxNzM4NTEwNzUyLCJleHAiOjE3MzkwMTA3NTJ9.SKzbY3OyOPxKScFVoid9JK387p04qj5izQ0XU9aiRyA

### 매장 호출
GET http://localhost:8080/shop/detail?name=백우동
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QxMEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NQU5BR0VSIiwiaWF0IjoxNzM4Mzk5NTY5LCJleHAiOjE3Mzg4OTk1Njl9.pyRRs2Ou7s4LPobcx0FC6eWSyU76iC-cCeRUeTmeE7U


### 매장 검색 (비슷한 이름 모두 검색)
GET http://localhost:8080/shop/search?keyword=우
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfTUVNQkVSIiwiaWF0IjoxNzM4NTQyMjcyLCJleHAiOjE3MzkxNDcwNzJ9.A_L3Y1lmbrhA-y-350WGLQEOZgmxd0VPKa11qjon6tA



### 모든 매장 호출
GET http://localhost:8080/shop
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QxMEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NQU5BR0VSIiwiaWF0IjoxNzM4Mzk5NTY5LCJleHAiOjE3Mzg4OTk1Njl9.pyRRs2Ou7s4LPobcx0FC6eWSyU76iC-cCeRUeTmeE7U


### 모든 매장 호출(가나다 정렬)
GET http://localhost:8080/shop/asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QxMEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NQU5BR0VSIiwiaWF0IjoxNzM4Mzk5NTY5LCJleHAiOjE3Mzg4OTk1Njl9.pyRRs2Ou7s4LPobcx0FC6eWSyU76iC-cCeRUeTmeE7U

### 모든 매장 호출(별점순 정렬)
GET http://localhost:8080/shop/star
Content-Type: application/json


### 모든 매장 호출(거리순 정렬)
GET http://localhost:8080/shop/distance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QxMEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NQU5BR0VSIiwiaWF0IjoxNzM4Mzk5NTY5LCJleHAiOjE3Mzg4OTk1Njl9.pyRRs2Ou7s4LPobcx0FC6eWSyU76iC-cCeRUeTmeE7U

{
  "lat": 37.48575204265654,
  "lng": 126.93135633587579
}


### 매장 평균 별점 확인
GET http://localhost:8080/shop/detail/rating?name=백다방
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QxMEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9NQU5BR0VSIiwiaWF0IjoxNzM4Mzk5NTY5LCJleHAiOjE3Mzg4OTk1Njl9.pyRRs2Ou7s4LPobcx0FC6eWSyU76iC-cCeRUeTmeE7U
